"""
Tests for the code generation modules.
"""

from __future__ import annotations

import json
import struct
from typing import Any

import pytest

from choreography.engine import run_choreography_engine
from code_generation.generator import run_code_generation
from code_generation.json_timeline import generate_json_timeline
from code_generation.csv_export import generate_csv
from code_generation.dmx_artnet import generate_dmx_artnet
from code_generation.arduino_mega import generate_arduino_mega


@pytest.fixture
def sample_timeline(
    minimal_analysis_result: dict[str, Any],
    small_fountain_config: dict[str, Any],
) -> dict[str, Any]:
    """Generate a sample show timeline for code generation tests."""
    from settings import WorkerSettings
    return run_choreography_engine(
        analysis_result=minimal_analysis_result,
        fountain_config=small_fountain_config,
        song_name="test_song",
        settings=WorkerSettings(),
    )


class TestJSONTimeline:
    def test_generates_valid_json(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_json_timeline(sample_timeline, small_fountain_config)
        assert result["platform"] == "json_timeline"
        assert len(result["files"]) >= 1

        json_file = result["files"][0]
        assert json_file["content_type"] == "text"
        parsed = json.loads(json_file["content"])
        assert parsed["version"] == "1.0"
        assert "tracks" in parsed

    def test_output_matches_timeline_schema(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_json_timeline(sample_timeline, small_fountain_config)
        json_file = result["files"][0]
        parsed = json.loads(json_file["content"])

        for track in parsed["tracks"]:
            assert "actuator_id" in track
            assert "actuator_type" in track
            assert "keyframes" in track
            for kf in track["keyframes"]:
                assert "time_ms" in kf
                assert "value" in kf
                assert "easing" in kf


class TestCSVExport:
    def test_generates_csv_with_header(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_csv(sample_timeline, small_fountain_config)
        assert result["platform"] == "csv"

        csv_file = result["files"][0]
        lines = csv_file["content"].split("\n")
        assert "timestamp_ms" in lines[0]
        assert "channel_id" in lines[0]
        assert "value" in lines[0]

    def test_csv_has_data_rows(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_csv(sample_timeline, small_fountain_config)
        csv_file = result["files"][0]
        data_lines = [l for l in csv_file["content"].split("\n") if l and not l.startswith("#")]
        assert len(data_lines) > 10  # Should have many frames


class TestDMXArtNet:
    def test_generates_binary_file(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_dmx_artnet(sample_timeline, small_fountain_config)
        assert result["platform"] == "dmx_artnet"

        ffshow_file = next(f for f in result["files"] if f["filename"].endswith(".ffshow"))
        import base64
        raw = base64.b64decode(ffshow_file["content_b64"])
        assert raw[:6] == b"FFSHOW"

    def test_binary_header_valid(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_dmx_artnet(sample_timeline, small_fountain_config)
        ffshow_file = next(f for f in result["files"] if f["filename"].endswith(".ffshow"))
        import base64
        raw = base64.b64decode(ffshow_file["content_b64"])

        magic, version, frame_rate, universe_count, frame_count = struct.unpack_from(">6sHHBI", raw, 0)
        assert magic == b"FFSHOW"
        assert version == 1
        assert frame_rate == 40
        assert universe_count >= 1
        assert frame_count > 0


class TestArduinoMega:
    def test_generates_ino_file(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_arduino_mega(sample_timeline, small_fountain_config)
        assert result["platform"] == "arduino_mega"

        ino_file = next(f for f in result["files"] if f["filename"].endswith(".ino"))
        content = ino_file["content"]
        assert "AUTO-GENERATED by FountainFlow" in content
        assert "#include <SD.h>" in content
        assert "void setup()" in content
        assert "void loop()" in content

    def test_generates_binary_sd_data(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        result = generate_arduino_mega(sample_timeline, small_fountain_config)
        bin_file = next(f for f in result["files"] if f["filename"] == "show_data.bin")
        import base64
        raw = base64.b64decode(bin_file["content_b64"])
        assert raw[:6] == b"FFSHOW"
        assert len(raw) > 15  # Header + at least 1 frame


class TestGeneratorDispatcher:
    def test_dispatches_all_platforms(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        from settings import WorkerSettings
        platforms = ["json_timeline", "csv", "dmx_artnet"]
        results = run_code_generation(
            show_timeline=sample_timeline,
            fountain_config=small_fountain_config,
            target_platforms=platforms,
            settings=WorkerSettings(),
        )
        assert len(results) == len(platforms)
        result_platforms = {r["platform"] for r in results}
        assert result_platforms == set(platforms)

    def test_falls_back_to_json_if_empty_platforms(
        self,
        sample_timeline: dict[str, Any],
        small_fountain_config: dict[str, Any],
    ) -> None:
        from settings import WorkerSettings
        results = run_code_generation(
            show_timeline=sample_timeline,
            fountain_config=small_fountain_config,
            target_platforms=[],
            settings=WorkerSettings(),
        )
        assert len(results) == 1
        assert results[0]["platform"] == "json_timeline"
